public with sharing class Demo {
    public Demo() {

    }
    public String getName() {
        // comment
        // comment
        // comment
                // comment
                        // comment
                                // comment
                                                                // comment




        Demo1 demo2 = new Demo1();
       return demo1.getName();
    }
}
