name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v2
      - name: 'install salesforce cli'
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.Dm }}
      - name: install delta app
        run: |
          sfdx plugins:install sfdx-git-delta
          git config remote.origin.fetch '+refs/head/*:refs/remote/origin/*'
          git fetch --all
          sfdx sgd:source:delta --to HEAD --from HEAD^ --output .
          ls

      - name: convert_source_format
        run: sfdx force:source:convert --sourcepath=force-app/main/default/lwc  --outputdir=convert
      - name: deploy source to org 
        run: sfdx force:source:deploy -x convert/package.xml 
