name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v2
      - name: 'install salesforce cli'
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.Dm }}
      - name: convert_source_format
        run: sfdx force:source:convert --sourcepath=force-app/main/default/classes  --outputdir=convert
      - name: deploy source to org 
        run: sfdx force:mdapi:deploy -d convert/package.xml 
